[www]
pm = dynamic
pm.max_children = 14
pm.start_servers = 4
pm.min_spare_servers = 2
pm.max_spare_servers = 6
pm.max_requests = 500
request_terminate_timeout = 120s
request_slowlog_timeout = 5s
slowlog = /var/www/storage/logs/php-fpm/php-fpm-www.slow.log
request_slowlog_trace_depth = 60
pm.status_path = /fpm-status
pm.status_listen = 0.0.0.0:9101
catch_workers_output = yes

[webhook]
user = www-data
group = www-data
listen = 9001
pm = static
pm.max_children = 6
pm.max_requests = 500
request_terminate_timeout = 30s
request_slowlog_timeout = 5s
slowlog = /var/www/storage/logs/php-fpm/php-fpm-webhook.slow.log
request_slowlog_trace_depth = 60
pm.status_path = /fpm-status
pm.status_listen = 0.0.0.0:9102
catch_workers_output = yes
clear_env = no
